steps:
  - name: gcr.io/cloud-builders/docker
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/koplak-api-cc:$COMMIT_SHA'
      - '.'
  - name: gcr.io/cloud-builders/docker
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/koplak-api-cc:$COMMIT_SHA'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'koplak-api-cc'
      - '--image=gcr.io/$PROJECT_ID/koplak-api-cc:$COMMIT_SHA'
      - '--region=us-central1'
      - '--cpu=1'
      - '--memory=2048Mi'
      - '--allow-unauthenticated'
      - '--set-secrets=DB_HOST=db_host:latest,DB_USERNAME=db_username:latest,DB_PASSWORD=db_password:latest,DB_NAME=db_name:latest,SECRET_KEY=secret_key:latest, REFRESH_TOKEN_KEY=refresh_token_key:latest'
images:
  - 'gcr.io/$PROJECT_ID/koplak-api-cc:$COMMIT_SHA'
logsBucket: 'gs://koplak-buckets/logs'